#!/bin/bash

username=$1
ip=$2
echo "IP: $ip"
while true ;
do
output=$(curl -sL http://$ip:9999)

if [ "$output" != "$username" ]; then
   echo "IP: $2"
   curl -sL http://$ip:9999 | figlet -f small | lolcat
   paplay alarm.wav
   sleep 1
   clear
else
	echo "IP: $ip";curl -sL http://$ip:9999 | figlet -f small | lolcat
	sleep 1
	clear
	
fi
done
